version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: clinicadb
      MYSQL_USER: clinicadbuser
      MYSQL_PASSWORD: clinicadbpassword
